### ISSUE TITLE
Non-root homebrew on Mac lab computers

### ISSUE THREAD

**Issue by learner-long-life** [TheEvergreenStateCollege/upper-division-cs-24-25#42]
We're able to install and run Homebrew as a non-root user on the lab computers in 2619, but in a somewhat arcane way.

https://superuser.com/a/1603383

https://nelsonaloysio.medium.com/installing-homebrew-without-sudo-5e708a929522

At some point we may need XCode tools, for better karma, or something

![image](https://github.com/user-attachments/assets/89880f1f-056d-4476-acd7-013404aa228e)

@absentbird @haydene907 if you're interested, I could use some help testing and documenting instructions for those adventurers willing to brave this config journey.

**Comment by haydene907** [comment]
I'm not very familiar with MacOS specifically, but I could help with some documentation. Would probably need to work through the instructions in the mac lab just to iron out exactly what needs to be done before putting pen to paper on how it works.

**Comment by learner-long-life** [comment]
`tmux`, `git`, `alacritty` are possible, as well as creating network servers that listen on non-privileged ports.

![image](https://github.com/user-attachments/assets/e5a10a0e-566c-45b0-9194-0fb1b456693c)

It's not portable, so when someone gets a setup they like on one lab computer, I think they're pretty much tied into logging back into it every time. And it will all get wiped yearly, which is probably for the best.

**Comment by learner-long-life** [comment]
Also complementary approach to a reproducible environment / alternative to GitPod, for those who don't want to give away their phone numbers.

https://ianthehenry.com/posts/how-to-learn-nix/installing-nix-on-macos/

**Comment by AkinaSS** [comment]
This looks interesting, although I don't know what's the exact usage for this, is it for everyone has their own version of terminal?

**Comment by haydene907** [comment]
Shaun added documentation under HomebrewInstall.md with commands that install homebrew without root privileges.
I tested these commands in the mac lab and they worked. If Homebrew is needed to be installed on a system simply follow instructions found in HomebrewInstall.md.

**Comment by learner-long-life** [comment]
> This looks interesting, although I don't know what's the exact usage for this, is it for everyone has their own version of terminal?

Sure, you can use it to install and run custom terminals instead of the iTerm2 default, and any other Mac app, for example Unity or Unreal engine, Minecraft, or a Java Development Kit for running Battlecode. Then you don't need to bring a laptop to class in order to participate fully.
